image: malkinfedor/golang-gitlab-image:1.15.1

variables:
  DOCKER_IMAGE_NAME: "hello-world" 
  DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
  DOCKER_REPO: "malkinfedor"
  
stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  script:
    - go test -short

race_detector:
  stage: test
  script:
    - go test -race -short

memory_sanitizer:
  stage: test
  script:
    - go test -msan -short

#code_coverage:
#  stage: test
#  script:
#    - make coverage

#code_coverage_report:
#  stage: test
#  script:
#    - make coverhtml
#  only:
#  - master

lint_code:
  stage: test
  script:
    - golint -set_exit_status

common-build:
  stage: build
  artifacts:
    paths:
      - golang-helloworld
    expire_in: 1 week
  script:
    - go build -i -v


docker-build:
  image: docker:19.03.13
  services:
    - docker:dind
  before_script:
    - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN}
  stage: build
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} .
    - docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_TAG}  
    - docker run ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_TAG} 
    - docker push ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
    - echo "The image was succesfully pushed:" ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_TAG}   

deploy-dev:
  stage: deploy
  image: junte/ssh-agent
  variables:
    # should be set up at Gitlab CI env vars
    SSH_PRIVATE_KEY: $SSH_DEV_PRIVATE_KEY
  script:
    - ssh root@ansible-jenkins.northeurope.cloudapp.azure.com "docker run -i ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_TAG}"
#  environment:
#      name: dev
#  only:
#    - dev
