FROM golang:1.15
MAINTAINER Alexander Susin <alexander.g.susin@gmail.com>

# Install golint
ENV GOPATH /go
ENV PATH ${GOPATH}/bin:$PATH
ENV LLVM_KEY_URL https://apt.llvm.org/llvm-snapshot.gpg.key

# Add support for https apt sources
RUN apt-get update && apt-get install apt-transport-https ca-certificates -y

# Add apt key for LLVM repository
RUN wget -O - $LLVM_KEY_URL | apt-key add -

# set CC env var for CLANG
ENV CC clang-6.0

#Install golint
RUN go get -u golang.org/x/lint/golint

# Add LLVM apt repository
RUN echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main" | tee -a /etc/apt/sources.list

# Install clang from LLVM repository
RUN apt-get update
RUN apt-get install -y --no-install-recommends clang-6.0
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install dep
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# Set Clang as default CC
ENV set_clang /etc/profile.d/set-clang-cc.sh
RUN echo "export CC=clang-6.0" | tee -a ${set_clang} && chmod a+x ${set_clang}
